import * as mdb from 'mdb-ui-kit';
require('../vendor/js/plugins/bootstrap-selectpicker.js');
require('../vendor/js/plugins/bootstrap-tagsinput.js');
require('../vendor/js/plugins/jasny-bootstrap.min.js');
require('../vendor/js/plugins/jquery.flexisel.js');
require('../vendor/js/plugins/bootstrap-datetimepicker.min.js');
require('../vendor/js/plugins/nouislider.min.js');
require('bootstrap-sweetalert/dist/sweetalert');
require('../vendor/codemirror/lib/codemirror.js');
require('../vendor/codemirror/mode/javascript/javascript.js');
require('../vendor/codemirror/mode/css/css.js');
require('../vendor/codemirror/addon/hint/show-hint.js');
require('../vendor/codemirror/addon/hint/css-hint.js');
require('../vendor/codemirror/addon/hint/javascript-hint.js');
