name: Reference design branch workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: build-docker-image
        run: make build-branch

      - id: login-to-dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: publish-docker-image
        run: make publish-branch-image

  deploy:
    needs: build
    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: build-docker-image
        run: make deploy-staging

