---
# Docker image name
customize_docker_image: obada/reference-design:wpdi

# Site name for the initial page
site_name: "World Data Products Reference Design"

# Logo path
customize_logo_path: https://www.wdpi.com/media/logo/websites/2/logo.png

# Logo text
customize_logo_text: "Blockchain Demo Site"

# Logo height
logo_height: 20

# Footer text
customize_footer_text: "© 2023 World Data Products, All Rights Reserved."

# Page background color
background_color: "#fff"

# Main text color
text_color: "#333"

# Main text size
text_size_base: 16px

# Links text color
link_color: "#0058a1"

# Background color for top navigation (header)
header_background_color: "#ffffff"

# Text color for top navigation (header)
header_text_color: "#333"

# Background color for bottom navigation (footer)
footer_background_color: "#434b52"

# Text color for bottom navigation (footer)
footer_text_color: "rgba(255,255,255,0.75)"

# Primary color
primary_color: "#00aa65"

